# Generated by Django 5.2.6 on 2026-10-01 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='商品名称')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='品牌')),
                ('model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='商品型号')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='商品分类')),
                ('product_url', models.URLField(blank=True, default='', max_length=500, verbose_name='商品链接')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='商品图片')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'is_deleted'], name='product_user_deleted_idx'), models.Index(fields=['user', 'name'], name='product_user_name_idx')],
            },
        ),
    ]
