# Generated by Django 5.2.6 on 2026-10-01 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='商品价格')),
                ('platform', models.CharField(blank=True, default='', max_length=50, verbose_name='平台')),
                ('recorded_date', models.DateField(verbose_name='价格记录日期')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_records', to='products.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品价格记录',
                'verbose_name_plural': '商品价格记录',
                'db_table': 'product_price_records',
                'ordering': ['-recorded_date', '-id'],
                'indexes': [models.Index(fields=['product', 'recorded_date'], name='product_price_date_idx'), models.Index(fields=['user', 'recorded_date'], name='product_price_user_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='product_price_positive_ck')],
            },
        ),
    ]
