# Generated by Django 5.2.6 on 2026-09-20 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='用户自定义账户名称', max_length=50, verbose_name='账户名称')),
                ('account_type', models.CharField(choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝'), ('bank', '银行卡'), ('credit_card', '信用卡'), ('other', '其他')], db_comment='账户类型：cash现金、wechat微信、alipay支付宝、bank银行卡、credit_card信用卡、other其他', default='other', max_length=20, verbose_name='账户类型')),
                ('initial_balance', models.DecimalField(db_comment='账户创建时的初始余额', decimal_places=2, default=0, max_digits=14, verbose_name='初始余额')),
                ('balance', models.DecimalField(db_comment='账户当前实际余额', decimal_places=2, default=0, max_digits=14, verbose_name='当前余额')),
                ('icon', models.CharField(blank=True, db_comment='账户图标标识', default='', max_length=100, verbose_name='图标')),
                ('color', models.CharField(blank=True, db_comment='账户展示颜色', default='', max_length=20, verbose_name='颜色')),
                ('sort_order', models.PositiveIntegerField(db_comment='账户列表排序值，值越小越靠前', default=0, verbose_name='排序')),
                ('is_default', models.BooleanField(db_comment='是否为用户默认账户', default=False, verbose_name='默认账户')),
                ('is_active', models.BooleanField(db_comment='账户是否启用', default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(db_comment='逻辑删除标记', default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='记录最后更新时间', verbose_name='更新时间')),
                ('user', models.ForeignKey(db_comment='账户所属用户', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
                'db_table': 'accounts',
                'db_table_comment': '用户资金账户表',
                'indexes': [models.Index(fields=['user', 'is_deleted', 'sort_order'], name='idx_account_user_list')],
            },
        ),
    ]
