# Generated by Django 5.2.6 on 2026-09-21 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_balance', models.DecimalField(db_comment='余额校准前的账户余额', decimal_places=2, max_digits=14, verbose_name='校准前余额')),
                ('new_balance', models.DecimalField(db_comment='余额校准后的账户余额', decimal_places=2, max_digits=14, verbose_name='校准后余额')),
                ('difference', models.DecimalField(db_comment='新余额减去旧余额的差额', decimal_places=2, max_digits=14, verbose_name='调整差额')),
                ('note', models.CharField(blank=True, db_comment='账户余额校准原因或备注', default='', max_length=255, verbose_name='校准说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='余额校准记录创建时间', verbose_name='创建时间')),
                ('account', models.ForeignKey(db_comment='被执行余额校准的账户', on_delete=django.db.models.deletion.PROTECT, related_name='balance_adjustments', to='accounts.account', verbose_name='账户')),
                ('user', models.ForeignKey(db_comment='执行余额校准的用户', on_delete=django.db.models.deletion.CASCADE, related_name='account_balance_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '账户余额校准记录',
                'verbose_name_plural': '账户余额校准记录',
                'db_table': 'account_balance_adjustments',
                'db_table_comment': '账户余额校准记录表',
                'indexes': [models.Index(fields=['user', 'account', 'created_at'], name='idx_balance_adjust_history')],
            },
        ),
    ]
