# Generated by Django 5.2.6 on 2026-09-21 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountbalanceadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(db_comment='账户之间转移的金额', decimal_places=2, max_digits=14, verbose_name='转账金额')),
                ('fee', models.DecimalField(db_comment='本次转账产生的手续费', decimal_places=2, default=0, max_digits=14, verbose_name='手续费')),
                ('transfer_time', models.DateTimeField(db_comment='用户实际发生转账的时间', verbose_name='转账时间')),
                ('note', models.CharField(blank=True, db_comment='转账备注', default='', max_length=255, verbose_name='备注')),
                ('status', models.CharField(choices=[('normal', '正常'), ('deleted', '已删除')], db_comment='转账状态：normal正常、deleted已删除', default='normal', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='转账记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='转账记录最后更新时间', verbose_name='更新时间')),
                ('source_account', models.ForeignKey(db_comment='资金转出的账户', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='accounts.account', verbose_name='转出账户')),
                ('target_account', models.ForeignKey(db_comment='资金转入的账户', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='accounts.account', verbose_name='转入账户')),
                ('user', models.ForeignKey(db_comment='转账记录所属用户', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '账户转账',
                'verbose_name_plural': '账户转账',
                'db_table': 'transfers',
                'db_table_comment': '账户转账记录表',
                'indexes': [models.Index(fields=['user', 'transfer_time'], name='idx_transfer_user_time'), models.Index(fields=['user', 'source_account', 'transfer_time'], name='idx_transfer_source_time'), models.Index(fields=['user', 'target_account', 'transfer_time'], name='idx_transfer_target_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_transfer_amount_positive'), models.CheckConstraint(condition=models.Q(('fee__gte', 0)), name='ck_transfer_fee_nonnegative'), models.CheckConstraint(condition=models.Q(('source_account', models.F('target_account')), _negated=True), name='ck_transfer_accounts_different')],
            },
        ),
    ]
