# Generated by Django 5.2.6 on 2026-09-22 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='收入或支出分类名称', max_length=50, verbose_name='分类名称')),
                ('category_type', models.CharField(choices=[('expense', '支出'), ('income', '收入')], db_comment='分类类型：expense支出、income收入', max_length=20, verbose_name='分类类型')),
                ('icon', models.CharField(blank=True, db_comment='分类图标标识', default='', max_length=100, verbose_name='图标')),
                ('color', models.CharField(blank=True, db_comment='分类展示颜色', default='', max_length=20, verbose_name='颜色')),
                ('sort_order', models.PositiveIntegerField(db_comment='分类排序，值越小越靠前', default=0, verbose_name='排序')),
                ('is_system', models.BooleanField(db_comment='是否为系统内置分类', default=False, verbose_name='系统分类')),
                ('is_active', models.BooleanField(db_comment='分类是否启用', default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(db_comment='分类逻辑删除标记', default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='分类创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='分类最后更新时间', verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, db_comment='分类所属用户，NULL表示系统默认分类', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'categories',
                'db_table_comment': '收入支出分类表',
                'indexes': [models.Index(fields=['user', 'category_type', 'is_deleted', 'sort_order'], name='idx_category_user_list'), models.Index(fields=['is_system', 'category_type', 'is_deleted'], name='idx_category_system')],
            },
        ),
    ]
