# Generated by Django 5.2.6 on 2026-10-01 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='默认货币')),
                ('theme', models.CharField(choices=[('light', '浅色'), ('dark', '深色'), ('system', '跟随系统')], default='system', max_length=20, verbose_name='主题模式')),
                ('page_size', models.PositiveIntegerField(default=20, verbose_name='分页数量')),
                ('budget_reminder_enabled', models.BooleanField(default=True, verbose_name='预算提醒开关')),
                ('budget_reminder_threshold', models.PositiveIntegerField(default=80, verbose_name='预算提醒阈值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='accounts.account', verbose_name='默认账户')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好',
                'db_table': 'user_preference',
            },
        ),
    ]
