# Generated by Django 5.2.6 on 2026-09-22 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_transfer'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', '支出'), ('income', '收入')], db_comment='账单类型：expense支出、income收入', max_length=20, verbose_name='账单类型')),
                ('amount', models.DecimalField(db_comment='账单金额，必须大于0', decimal_places=2, max_digits=14, verbose_name='金额')),
                ('transaction_time', models.DateTimeField(db_comment='收入或支出实际发生时间', verbose_name='账单时间')),
                ('merchant', models.CharField(blank=True, db_comment='消费商户或收入来源', default='', max_length=100, verbose_name='商户')),
                ('note', models.CharField(blank=True, db_comment='账单备注', default='', max_length=255, verbose_name='备注')),
                ('status', models.CharField(choices=[('normal', '正常'), ('deleted', '已删除')], db_comment='账单状态：normal正常、deleted已删除', default='normal', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='账单创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='账单最后更新时间', verbose_name='更新时间')),
                ('account', models.ForeignKey(db_comment='账单关联账户', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.account', verbose_name='账户')),
                ('category', models.ForeignKey(blank=True, db_comment='账单关联分类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.category', verbose_name='分类')),
                ('user', models.ForeignKey(db_comment='账单所属用户', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '账单',
                'verbose_name_plural': '账单',
                'db_table': 'transactions',
                'db_table_comment': '收入支出账单表',
                'indexes': [models.Index(fields=['user', 'transaction_time'], name='idx_tx_user_time'), models.Index(fields=['user', 'transaction_type', 'transaction_time'], name='idx_tx_user_type_time'), models.Index(fields=['user', 'account', 'transaction_time'], name='idx_tx_user_account_time'), models.Index(fields=['user', 'category', 'transaction_time'], name='idx_tx_user_category_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_tx_amount_positive')],
            },
        ),
    ]
