# Generated by Django 5.2.6 on 2026-10-01 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transactions/%Y/%m/', verbose_name='账单图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='transactions.transaction', verbose_name='账单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_images', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '账单图片',
                'verbose_name_plural': '账单图片',
                'db_table': 'transaction_image',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction', 'user'], name='transaction_transac_6e21e8_idx')],
            },
        ),
    ]
