# Generated by Django 5.2.6 on 2026-09-19 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='userprofile',
            table_comment='用户扩展资料表',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, db_comment='用户头像文件路径', null=True, upload_to='avatars/%Y/%m/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, db_comment='用户出生日期', null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(db_comment='用户默认货币，例如 CNY', default='CNY', max_length=10, verbose_name='默认货币'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], db_comment='性别：0未知，1男，2女', default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, db_comment='用户昵称', default='', max_length=50, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, db_comment='用户手机号，唯一', max_length=20, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(db_comment='用户默认时区', default='Asia/Shanghai', max_length=50, verbose_name='时区'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='记录最后更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(db_comment='关联的系统用户', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
