# Generated by Django 5.2.6 on 2026-09-28 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='目标名称')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='目标金额')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='当前已存金额')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('icon', models.CharField(blank=True, default='', max_length=100, verbose_name='图标')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='颜色')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '已暂停'), ('completed', '已完成')], default='active', max_length=20, verbose_name='目标状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '储蓄目标',
                'verbose_name_plural': '储蓄目标',
                'db_table': 'savings_goals',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'status', 'is_deleted'], name='saving_user_status_idx'), models.Index(fields=['user', 'deadline'], name='saving_user_deadline_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='saving_target_positive_ck'), models.CheckConstraint(condition=models.Q(('current_amount__gte', 0)), name='saving_current_nonnegative_ck')],
            },
        ),
    ]
