# Generated by Django 5.2.6 on 2026-09-28 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('deposit', '存入'), ('withdraw', '取出')], max_length=20, verbose_name='流水类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('before_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='变动前金额')),
                ('after_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='变动后金额')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='savings.savingsgoal', verbose_name='储蓄目标')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '储蓄流水',
                'verbose_name_plural': '储蓄流水',
                'db_table': 'savings_records',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['goal', 'created_at'], name='saving_record_goal_idx'), models.Index(fields=['user', 'created_at'], name='saving_record_user_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='saving_record_amount_positive_ck'), models.CheckConstraint(condition=models.Q(('before_amount__gte', 0)), name='saving_record_before_nonnegative_ck'), models.CheckConstraint(condition=models.Q(('after_amount__gte', 0)), name='saving_record_after_nonnegative_ck')],
            },
        ),
    ]
