"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-q%la%mm@&lad78q52=r))w0r$kqnjt%n0fui*9zn3i09c@e+th"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 第三方
    "rest_framework",
    # SimpleJWT Refresh Token 黑名单功能。
    "rest_framework_simplejwt.token_blacklist",
    # 本地应用
    "apps.users.apps.UsersConfig",
    "apps.accounts.apps.AccountsConfig",
    "apps.categories.apps.CategoriesConfig",
    "apps.transactions.apps.TransactionsConfig",
    "apps.budgets.apps.BudgetsConfig",
    "apps.savings.apps.SavingsConfig",
    "apps.dashboard.apps.DashboardConfig",
    "apps.products.apps.ProductsConfig",
    "apps.tags.apps.TagsConfig",
    # "apps.budgets",
    # "apps.savings",
    # "apps.dashboard",
    # "apps.products",
    # "apps.tags",
    "apps.preferences.apps.PreferencesConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}
# ==========================================
# Redis Cache
# ==========================================
# 用于存储：
# 1. 找回密码验证码；
# 2. 密码重置临时 Token；
# 3. 后续其它短期缓存数据。
#
# 当前使用本机 Redis：
# 127.0.0.1:6379
#
# /1 表示使用 Redis 的 1 号数据库，
# 避免与其它 Redis 数据混在一起。
# ==========================================
REDIS_HOST = os.getenv(
    "REDIS_HOST",
    "127.0.0.1",
)

REDIS_PORT = os.getenv(
    "REDIS_PORT",
    "6379",
)

REDIS_PASSWORD = os.getenv(
    "REDIS_PASSWORD",
    "",
)

REDIS_DB = os.getenv(
    "REDIS_DB",
    "1",
)
CACHES = {
    "default": {
        "BACKEND": ("django.core.cache.backends.redis.RedisCache"),
        "LOCATION": (
            f"redis://:{REDIS_PASSWORD}" f"@{REDIS_HOST}:{REDIS_PORT}" f"/{REDIS_DB}"
        ),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"
LANGUAGE_CODE = "zh-hans"
TIME_ZONE = "Asia/Shanghai"


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ==============================
# Django REST Framework 配置
# ==============================
REST_FRAMEWORK = {
    # JWT 身份认证
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # 默认要求登录
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    # 全局异常处理
    "EXCEPTION_HANDLER": ("common.exceptions.handler." "custom_exception_handler"),
    "DEFAULT_PAGINATION_CLASS": ("common.pagination.pagination." "StandardPagination"),
    "PAGE_SIZE": 20,
    # ==============================
    # 日期时间统一返回格式
    # ==============================
    #
    # 接口中的 DateTimeField 统一返回：
    # 2026-09-20 22:41:23
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
    # 日期统一返回：
    # 2026-09-20
    "DATE_FORMAT": "%Y-%m-%d",
    # 时间统一返回：
    # 22:41:23
    "TIME_FORMAT": "%H:%M:%S",
}


# ==============================
# JWT 配置
# ==============================
SIMPLE_JWT = {
    # Access Token 有效时间
    # Access Token 用于正常业务接口访问
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    # Refresh Token 有效时间
    # Access Token 过期以后，可以使用 Refresh Token 获取新 Token
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # 使用 Refresh Token 刷新时，同时生成一个新的 Refresh Token
    "ROTATE_REFRESH_TOKENS": True,
    # 暂时不启用旧 Refresh Token 黑名单
    # 后续实现“退出登录”功能时再开启
    "BLACKLIST_AFTER_ROTATION": True,
    # HTTP 请求头中的 Token 类型
    # 前端请求格式：
    # Authorization: Bearer xxxxx
    "AUTH_HEADER_TYPES": ("Bearer",),
    # Django User 模型中作为用户唯一标识的字段
    "USER_ID_FIELD": "id",
    # JWT Payload 中保存用户 ID 的字段名称
    "USER_ID_CLAIM": "user_id",
    # ==============================
    # 密码修改后自动废弃旧 Token
    # ==============================
    #
    # 开启后，SimpleJWT 会在 Token 中记录
    # 与用户当前密码哈希相关的撤销校验信息。
    #
    # 用户修改密码以后，
    # auth_user.password 会发生变化，
    # 之前签发的 JWT 将无法继续通过认证。
    "CHECK_REVOKE_TOKEN": True,
}
