# Generated by Django 5.2.6 on 2026-09-26 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_type', models.CharField(choices=[('overall', '总预算'), ('category', '分类预算')], max_length=20, verbose_name='预算类型')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年份')),
                ('month', models.PositiveSmallIntegerField(verbose_name='月份')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='预算金额')),
                ('alert_threshold', models.DecimalField(decimal_places=2, default=80, max_digits=5, verbose_name='提醒阈值')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='categories.category', verbose_name='预算分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '预算',
                'verbose_name_plural': '预算',
                'db_table': 'budgets',
                'ordering': ['-year', '-month', '-id'],
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='budget_user_month_idx'), models.Index(fields=['user', 'budget_type'], name='budget_user_type_idx'), models.Index(fields=['user', 'category', 'year', 'month'], name='budget_category_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='budget_month_range_ck'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='budget_amount_positive_ck'), models.CheckConstraint(condition=models.Q(('alert_threshold__gt', 0), ('alert_threshold__lte', 100)), name='budget_alert_range_ck'), models.CheckConstraint(condition=models.Q(models.Q(('budget_type', 'overall'), ('category__isnull', True)), models.Q(('budget_type', 'category'), ('category__isnull', False)), _connector='OR'), name='budget_type_category_ck'), models.UniqueConstraint(fields=('user', 'category', 'year', 'month'), name='budget_category_unique')],
            },
        ),
    ]
